### ISSUE TITLE
Configuration file is not using visibility

### ISSUE THREAD

**Issue by ppiwow-apay** [vippsas/backstage-azure-resources-backend#5]
Hi,

It seems that configuration interface is not using: https://backstage.io/docs/conf/defining/#visibility

It cause that secrets are displayed as a plain text in dev tools plugin:

https://github.com/backstage/backstage/blob/master/plugins/devtools/README.md#config

Is it possible to change it and mark this?

**Comment by ehrnst** [comment]
@tinolazreg since i dont work at Vipps anymore. Can you help me out with finding some contributors? Or you can merge it in to the backstage repo, where stuff like this probably will be fixed quickly.

I dont belive this was an issue earlier, as the devtools plugin didnt exist, and we used managed identity our self.

**Comment by ppiwow-apay** [comment]
any updates on PR, fix seems pretty easy?
